import type { Metadata } from "next";
import { Russo_One } from "next/font/google";
import { Zilla_Slab } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";

const russoOne = Russo_One({
  subsets: ["latin"],
  weight: "400",
});
const zillaSlab = Zilla_Slab({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={zillaSlab.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
